### PR TITLE
Test if the BaseOS CI enables the rhel-7-extras repository on RHEL 7

### PR DESCRIPTION
**Pull request by spetrosi**

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest pending]

**Comment by spetrosi** [comment]
[citest pending]

**Comment by spetrosi** [comment]
Hi @martinpitt, the rhel-7-server-extras repo is now being added in the BaseOS CI. Do you know how to fix the failings in `RHEL-7.9-20200917.0/ansible-2.9/(citool)`, `RHEL-8.3.0-20201009.2/ansible-2.9/(citool) `, and `RHEL-8.4.0-20210503.1/ansible-2.9/(citool)` tests?

**Comment by martinpitt** [comment]
@spetrosi : Argh, we already saw something similar [here](https://github.com/linux-system-roles/cockpit/pull/40#discussion_r741071249), but I thought that was fixed by not testing for tests/roles/linux-system-roles.certificate/.git/HEAD any more, but directly for the directory, with `when: not 'roles/linux-system-roles.certificate' is exists`.

So apparently roles/linux-system-roles.certificate does not exist for the ansible test, but git says "already exists and is not an empty directory.". So possibly it is a broken symlink? Do you have access to these machines and can check what exactly it is? Or perhaps temporarily add a commit here which does an `ls -lR`, so that we can see what on earth is going on there?

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
> @spetrosi : Argh, we already saw something similar [here](https://github.com/linux-system-roles/cockpit/pull/40#discussion_r741071249), but I thought that was fixed by not testing for tests/roles/linux-system-roles.certificate/.git/HEAD any more, but directly for the directory, with `when: not 'roles/linux-system-roles.certificate' is exists`.
> 
> So apparently roles/linux-system-roles.certificate does not exist for the ansible test, but git says "already exists and is not an empty directory.". So possibly it is a broken symlink? Do you have access to these machines and can check what exactly it is? Or perhaps temporarily add a commit here which does an `ls -lR`, so that we can see what on earth is going on there?

I've pushed a commit that does `ls -lR` in `tests_certificate.yml`. Waiting for the results.

**Comment by spetrosi** [comment]
I am not able to find if ``not 'roles/linux-system-roles.certificate' is exists` works in ansible.
I see two variants how to make this work:

1. This must be done in tasks like this:
```
- name: Check the roles/linux-system-roles.certificate directory
  stat:
    path: roles/linux-system-roles.certificate
  register: __cockpit_certificate_directory

    - name: Download current linux-system-roles.certificate
      git:
        repo: https://github.com/linux-system-roles/certificate/
        dest: roles/linux-system-roles.certificate
        version: master
        depth: 1
      become: false
      # skip this for RHEL downstream tests, which define $BEAKERLIB
      when:
        - lookup('env', 'BEAKERLIB') | length == 0
        - not __cockpit_certificate_directory.stat.exists
```

2. Add `force: true` to the current git task.

@martinpitt does this make sense and what variant sounds better to you?

**Comment by martinpitt** [comment]
> I am not able to find if ``not 'roles/linux-system-roles.certificate' is exists` works in ansible.

It at least works with Fedora 35's (I tested it locally, and it checks out git exactly if it doesn't exist yet), and also with Ubuntu 20.04 (where the "Integration test / ubuntu" runs).

Also, the `ls -lR` in the [log](https://152.19.134.199/groups/linuxsystemroles/logs/lsr-citool_cockpit-44-393a2fc_20211110-131546/artifacts/tests_certificate-FAILED.log) shows that the `git` task is outright lying -- tests/roles/ only has the `linux-system-roles.cockpit` symlink, but no `linux-system-roles.certificate`. However, that is actually surprising -- the previous playbook ought to have checked it out, unless each playbook is running in a different directory.

I don't quite like 2, as it does unnecessary work, and possibly clobbers local changes, which is annoying for development. If solution (1) works, fine for me, but I don't believe that the root cause is understood yet -- this needs reproducing and investigating locally. How can these "citool" runs be done locally?

**Comment by richm** [comment]
> > I am not able to find if ``not 'roles/linux-system-roles.certificate' is exists` works in ansible.
> 
> It at least works with Fedora 35's (I tested it locally, and it checks out git exactly if it doesn't exist yet), and also with Ubuntu 20.04 (where the "Integration test / ubuntu" runs).
> 
> Also, the `ls -lR` in the [log](https://152.19.134.199/groups/linuxsystemroles/logs/lsr-citool_cockpit-44-393a2fc_20211110-131546/artifacts/tests_certificate-FAILED.log) shows that the `git` task is outright lying -- tests/roles/ only has the `linux-system-roles.cockpit` symlink, but no `linux-system-roles.certificate`. However, that is actually surprising -- the previous playbook ought to have checked it out,

The way CI works is this:
For each test playbook in tests/tests_*.yml
  create VM
  run a single test playbook in that VM
  destroy the VM

So if by "previous playbook" you mean the "previous test playbook", then that ran in a completely different VM which was destroyed.

> unless each playbook is running in a different directory.

Each test playbook runs in a different VM

> 
> I don't quite like 2, as it does unnecessary work, and possibly clobbers local changes, which is annoying for development. If solution (1) works, fine for me, but I don't believe that the root cause is understood yet -- this needs reproducing and investigating locally. How can these "citool" runs be done locally?

**Comment by martinpitt** [comment]
Thanks -- so we actually *should* expect the checkout to not exist, and the `ls` is right. But this then also means that the `if exists` check was working correctly (and thus your (1) proposal shouldn't make a difference), as it did let the `git:` role run. So something is wrong with the git clone itself, and there's something really funky going on on the file system.

**Comment by richm** [comment]
How is it that https://github.com/linux-system-roles/certificate/blob/master/tests/tasks/setup_ipa.yml#L12-L19 this works for the certificate role testing?

**Comment by spetrosi** [comment]
That's a spooky thing going on, this works just fine on other OSes

**Comment by spetrosi** [comment]
Maybe we can run this `git` module with `force: true` once to force create the repo?

**Comment by martinpitt** [comment]
Fun, now two tests checked out git alright, but failed later on, and [this one](https://152.19.134.199/groups/linuxsystemroles/logs/lsr-citool_cockpit-44-1423482_20211110-171814/artifacts/tests_certificate_runafter-FAILED.log) failed in git again, but the _runafter test doesn't have the `ls -lR` debug step. Yay heisenbugs!

**Comment by spetrosi** [comment]
> [this one](https://152.19.134.199/groups/linuxsystemroles/logs/lsr-citool_cockpit-44-1423482_20211110-171814/artifacts/tests_certificate_runafter-FAILED.log)

I've only added `lsr -lR` in `tests_certificate.yml`, not `tests_certificate_runafter.yml` as only tests_certificate was failing.

**Comment by spetrosi** [comment]
Oh lol, so `tests_certificate.yml` and `tests_certificate_runafter.ym` does completely the same thing, but the thing is to work in one test and not in the other. That's some kind of magic.

Anyway, not this git module works. The new failing task is `cockpit works with TLS and expected certificate`. Again, it fails only on one OS. Really weird. Anyway, BaseOS CI enables the `rhel-7-server-extras` repo just fine, so I am closing it.

**Pull request closed without merging**
