### PR TITLE
Refactoring the cockpit role

### PR DESCRIPTION
**Pull request by i386x**
# Changes Summary
## Variables
All variables described in this section are exposed to the user for overriding.
I split the content of `cockpit_packages` between two `cockpit_base_packages` and `cockpit_extra_packages` role variables. `cockpit_base_packages` contains packages that provide basic Cockpit functionality and `cockpit_extra_packages` contains packages that extend Cockpit functionality. Maybe it is worth to move some packages from `cockpit_base_packages` into a new role variable called `cockpit_minimal_packages`, where only packages that are needed to successfully start the Cockpit service should be listed (`cockpit`?).
The value of `cockpit_enablerepo` is now computed with the respect to underlying Linux distribution. If it is empty, `enablerepo` feature is not used.
I renamed `cockpit_daemon` to `cockpit_service`, because the value of this variable is used to start the service via `service` Ansible module.
The value of `sleep` parameter of `service` Ansible module used in `handlers/main.yml` to restart Cockpit service can be now set via `cockpit_restart_delay` variable.
The content of `tasks/variables.yml`, `vars/Fedora-30.yml`, `vars/RedHat-7.yml`, and `vars/RedHat-8.yml` was distributed between `defaults/main.yml` and `vars/main.yml`.
## Tasks
The content of `tasks/setup-RedHat.yml` was inlined into `tasks/main.yml`.
The Debian parts of `tasks/main.yml` was temporarily removed as I cannot see `setup-Debian.yml` in the `tasks` directory.
Notes to `tasks/main.yml` architecture:
1. First, install the packages needed by Cockpit service to start successfully.
1. Enable and start the Cockpit service.
1. Install the extra packages. If something has changed (i.e. a new package was successfully installed), the handler is notified which cause Cockpit service to be restarted.
The reason not to install all of the packages in one step is that if the user has already Cockpit service enabled and started, the second step is skipped by Ansible even if new Cockpit packages were successfully installed (hence my proposal above to move Cockpit core packages to the new role variable `cockpit_minimal_packages`, the rest of `cockpit_base_packages` can be then installed in one step together with `cockpit_extra_packages`).
## Tests
I removed `tests/inventory` from the repo because it does not contain (remote) machine names (except localhost) to be configured by Ansible when running a playbook or that names are not defined anywhere (i.e. there is no script or Vagrantfile that can prepare virtual machines with such names). In our test use case, we run tests either on virtual machine launched by dynamic inventory script (concretely [standard-inventory-qcow2](https://pagure.io/standard-test-roles/blob/master/f/inventory/standard-inventory-qcow2)) or via Molecule (currently only `tests_default.yml`).
`tests/tests_default.yml` was a bit adjusted and a symbolic link to the role top level directory was added to make it possible to run `tests_default.yml` from `tests` directory via `ansible-playbook` command.
## Docs
All changes were reflected in `README.md`.

### CODE REVIEW

**Comment by tabowling** [comment]
@t-woerner @pcahyna  does this meet the newly updated standards and framework?  Should I merge it or does other work need to be completed?

**Comment by i386x** [comment]
Hello Terry, it must be adjusted first. There are several differences against standards.

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
Please rebase

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest]

**Comment by tabowling** [comment]
Closing this as I'm not sure it aligned with other standards the team had identified.  I am sure this role would benefit from improvements, so please re-submit after review of the latest standards. Contact @richm with any questions.

**Pull request closed without merging**
