### PR TITLE
[citest skip] workflows: Add integration-tests for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by martinpitt**
The current LTS 22.04 is the more interesting target. This detects bugs
like [1]. Keep 20.04 running as well for the time being.

[1] https://github.com/linux-system-roles/certificate/pull/130

----

 - Requires https://github.com/linux-system-roles/certificate/pull/130 to land first

### CODE REVIEW

**Comment by martinpitt** [comment]
[aha](https://github.com/linux-system-roles/cockpit/runs/7579554985?check_suite_focus=true#step:4:361), this needs fixing in lsr.certificate:
```
TASK [linux-system-roles.certificate : Ensure certificate role dependencies are installed] ***
task path: /home/runner/work/cockpit/cockpit/tests/roles/linux-system-roles.certificate/tasks/main.yml:5
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python-pyasn1' is available"}
```
No python 2 any more!

**Comment by richm** [comment]
integration tests pass on ubuntu - does this mean the certificate role change is working?

**Comment by martinpitt** [comment]
@richm The blocking change landed. I suppose you retried the failing test afterwards? This needs rebasing now due to the conflict. I'm on PTO until Aug 30, I can't do that until then. Please feel free to resolve and force-push to my branch to get this out of the way! Otherwise I'll do that in 11 days. Thanks!

**Comment by richm** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Pull request merged**
