### PR TITLE
update tox-lsr version to 2.8.0

### PR DESCRIPTION
**Pull request by spetrosi**
New version adds check for proper commenting of the ansible_managed var

### CODE REVIEW

**Comment by martinpitt** [comment]
Wait, whaat? *all* green? :clap: thanks @spetrosi !

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
@richm : Tests here have rhel-8 == 8.5 and rhel-8-y == 8.6. So maybe we need to land this first before #46?

**Comment by richm** [comment]
> @richm : Tests here have rhel-8 == 8.5 and rhel-8-y == 8.6. So maybe we need to land this first before #46?

1) tox based CI does not affect the ansible-x/platform-y based CI - so it doesn't matter
2) I had a question about this PR for @spetrosi so let's hold off
3) I recently made some fixes for CI which is probably why this PR is all green

**Comment by spetrosi** [comment]
Yeah green tests are not related to this PR. The PR is ready to merged now.

**Pull request merged**
